language: java
jdk:
  - openjdk8

env:
  global:
    - CC_TEST_REPORTER_ID=625f81170e5e1f800835a00456bdea0a81029eb3a76834c21aed333ab3602593

addons:
  sonarcloud:
    organization: "seancarroll-github"
    token:
      secure: "A3Ym1LnQVo8nCJN9UqSM37tkrLNUBHfyzjoEgLI1jG/R7Lh433FESzkFNz5hOd6ON/Y+Jg2CNPg36rvfmvL9u2iGrz7vikEMRjRtxLKKoRzu+bXP3x5r5J0MhREPPBkGDAf1CdmA2akGxRj6sU3VikwdHZeCNtFGHROctsBhP0PgYtYJlZH7QqP3jiI4S/YKRxKqLnd5PZYeA1CrwbfSGc+H2OsUe7wXAM8SxExTrUFr/EVXuc8979UrpSerZHqG9QammrVawFJL9wr/iwcLDjyfmojjLtZ43VfRmz/meDkhzZPLC447j3G9a1OJ/RLtE8PfC4GOqFVSGHT67r2+MMjRaQJKMY/DJa2G/eswlBmibTcX5zzisbQkZ5rErNY4b2qGlcCwuLmavTMCVFug/D8sHd4Ygp5sCxU8SvtdmbwVua0W4EBWJFJFLwrcpsGpyoDB7IbC2Ckjg7MPW40Lrc/BHpocN3Y06aBITfufHOXpgwF60Lrjr3VBHNSHhR9foYPuUgfxXZsjXSu4KVkQwLsTTJC0iVsMxtj4LRGXaXTT2C1sFcO9NbPoy+w2gIMf2f1hPwx7wZioZJLUKq0yLa8Wxq2ERYGWvNlHqFtU9WiyGKCjA1rPgQil+dNUIpE6HIFTWyfYhFvq+sFipsuAJDeil+CbJvI5MVSudnK9JHA="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=seancarroll_jfluentvalidation -Pcode-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - JACOCO_SOURCE_PATH=jfluentvalidation-core/src/main/java ./cc-test-reporter format-coverage ./jfluentvalidation-core/target/site/jacoco/jacoco.xml -d -t jacoco
#  - JACOCO_SOURCE_PATH=./jfluentvalidation-spring/src/main/java ./cc-test-reporter format-coverage ./target/site/jacoco-aggregate/jacoco.xml -d -t jacoco
#  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
  - ./cc-test-reporter upload-coverage
