language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "seancarroll-github"
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - snyk monitor


script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=seancarroll_jfluentvalidation -Pcode-coverage
